baseurl      = "https://fedeztk.github.io"
title        = "Federico Serra"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
publishDir = "docs"

[author]
    name = "Federico Serra"

[params]
  dateform        = "2 Jan 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006 15:04"

  # Subtitle for home
  homeSubtitle = "You can find me on:"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  enableThemeToggle = true

  # Metadata mostly used in document's head
  # description = "My new homepage or blog"
  # keywords = "homepage, blog"
  # images = [""]

  # Social icons
  [[params.social]]
  	name = "github"
  	url = "https://github.com/fedeztk"
  [[params.social]]
    name = "codeberg"
    url = "https://codeberg.org/fedeztk"
  [[params.social]]
    name = "gitlab"
    url = "https://gitlab.com/fedeztk"
  [[params.social]]
  	name = "mastodon"
  	url = "https://mastodon.social/web/@fedeztk"
  [[params.social]]
  	name = "email"
  	url = "mailto:fedeztk@tutanota.com"

  [params.footer]
    trademark = true
    rss = true
    copyright = true
    author = true

    topText = []
    # bottomText = [
    #   "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
    #   "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"
    # ]

  [params.portrait]
    path     = "/logo.jpg"
    alt      = "Portrait"
    # maxWidth = "50px"

  [params.logo]
    logoMark     = ">"
    logoText = "fedeztk ~"
    logoHomeLink = "/"
    logoCursorColor    = "#1C71D8"


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Federico Serra"
    subtitle = ""
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects"
  # [[menu.main]]
  #   identifier = "blog"
  #   name       = "Blog"
  #   url        = "/posts"
  [[menu.main]]
    identifier = "notes"
    name       = "Notes"
    url        = "/notes"
